<?php
//file : app/config/constants.php

return [

	'gw_nw_measurment' => 'Grams',
	'width_length_measurment' => 'mm',	
	'rn' => 'Price of Weight',
	'dp' => 'Price of Diamonds',
	'gp' => 'Price of Gemstones',
	'pp' => 'Price of Pearls',
	'polkip' => 'Price of Polki',
	'bp' => 'Price of Beads',
	'op' => 'Other Charges',
	'mp' => 'Making Charges',
	'hc' => 'Handling Charges',
	'withoutgst' => 'Sub Total',
	'cgst' => 'CGST',
	'sgst' => 'SGST',
	'gt' => 'Grand Total',
	'carat' => 'Carat',
	'carat_meas' => 'K',
	'if_order_empty' => 'Oops! Seems like your cart is empty.',
	'if_coupon_empty' => 'Oops! No data found.',
	'if_mytickets_empty' => 'Oops! No data found.',
	'purity' => 'Purity',
	'invoiceprefix' => 'JBN',
	'invoiceprefixoper' => '-',
	'cgstlabel' => 'CGST @ 1.5%',
	'sgstlabel' => 'SGST @ 1.5%',
	'igstlabel' => 'IGST @ 3%',
	'gstcgstonshipping' => 'CGST @ 9%',
	'gstsgstonshipping' => 'SGST @ 9%',
	'gstigstonshipping' => 'IGST @ 18%',
	'fixcgst' => '229.00',
	'fixsgst' => '229.00',
	'shippinglogistic' => '2542.00',
	'fixigst' => '458.00',
	'LabelHSNCode' => 'HSN Code',
	'HSNCode1' => '71131930',
	'HSNCode2' => '996531',
	'repeestring' => 'Rs: ',
];
